on jump:
	if {RPG현재직업::%player's uuid%} is set:
		if player is sneaking:
			push player forwards at speed 1
			push player upwards at speed 1
			set {더블점프중::%player%} to "점프중"

#여기부터 내가 처음으로 만듬
on jump:
	if {점프중::%player%} is not set:
		set {점프중::%player%} to true
		wait for 3 second
		delete {점프중::%player%}
	if {점프중::%player%} is set:
		push player forwards at speed 1
		push player upwards at speed 1
		delete {점프중::%player%}
		set {더블점프중::%player%} to "점프중"